# Generated by Django 2.1.14 on 2020-11-06 12:27

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfallback.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        ('core', '0009_mutationlog_client_mutation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPlan',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ContributionPlanId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContributionPlanUUID', default=uuid.uuid4, max_length=24, unique=True)),
                ('version', models.IntegerField()),
                ('active', models.BooleanField(db_column='Active')),
                ('code', models.CharField(blank=True, db_column='ContributionPlanCode', max_length=255, null=True)),
                ('periodicity', models.IntegerField()),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('amendment', models.IntegerField()),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated')),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom')),
                ('date_valid_to', core.fields.DateTimeField(verbose_name='DateValidTo')),
                ('benefit_plan', models.ForeignKey(db_column='BenefitPlanUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplan_CreatedUUID', to='core.InteractiveUser')),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplan_UpdatedUUID', to='core.InteractiveUser')),
            ],
            options={
                'db_table': 'tblContributionPlan',
            },
        ),
        migrations.CreateModel(
            name='ContributionPlanBundle',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ContributionPlanBundleId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContributionPlanBundleUUID', default=uuid.uuid4, max_length=24, unique=True)),
                ('version', models.IntegerField()),
                ('active', models.BooleanField(db_column='Active')),
                ('code', models.CharField(blank=True, db_column='ContributionPlanBundleCode', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='ContributionPlanBundleName', max_length=255, null=True)),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated')),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom')),
                ('date_valid_to', core.fields.DateTimeField(verbose_name='DateValidTo')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundle_CreatedUUID', to='core.InteractiveUser')),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundle_UpdatedUUID', to='core.InteractiveUser')),
            ],
            options={
                'db_table': 'tblContributionPlanBundle',
            },
        ),
        migrations.CreateModel(
            name='ContributionPlanBundleDetails',
            fields=[
                ('id', models.AutoField(db_column='ContributionPlanBundleDetailsId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContributionPlanBundleDetailsUUID', default=uuid.uuid4, max_length=24, unique=True)),
                ('version', models.IntegerField()),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated')),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom')),
                ('date_valid_to', core.fields.DateTimeField(verbose_name='DateValidTo')),
                ('active', models.BooleanField(db_column='Active')),
                ('contribution_plan', models.ForeignKey(db_column='ContributionPlanUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlan')),
                ('contribution_plan_bundle', models.ForeignKey(db_column='ContributionPlanBundleUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlanBundle')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundledetails_CreatedUUID', to='core.InteractiveUser')),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundledetails_UpdatedUUID', to='core.InteractiveUser')),
            ],
            options={
                'db_table': 'tblContributionPlanBundleDetails',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
