# Generated by Django 3.0.3 on 2020-11-20 11:43

import core.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contributionplanbundledetails',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='contributionplanbundledetails',
            name='legacy_id',
            field=models.UUIDField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='contributionplanbundledetails',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contributionplanbundledetails',
            name='validity_to',
            field=core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='date_valid_to',
            field=core.fields.DateTimeField(db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplan_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplan_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='uuid',
            field=models.CharField(db_column='ContributionPlanUUID', default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='date_valid_to',
            field=core.fields.DateTimeField(db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundle_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundle_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='uuid',
            field=models.CharField(db_column='ContributionPlanBundleUUID', default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundledetails',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundledetails',
            name='date_valid_to',
            field=core.fields.DateTimeField(db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplanbundledetails',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundledetails_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplanbundledetails',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributionplanbundledetails_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplanbundledetails',
            name='uuid',
            field=models.CharField(db_column='ContributionPlanBundleDetailsUUID', default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
